apiVersion: v1
kind: Service
metadata:
  name: thinkynxapp-svc
  labels:
    app: thinkynxapp
spec:
  type: NodePort
  selector:
    app: thinkynxapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30007 # 30000-32767