name: Deploy helm CHART IN kubernetes
on: 
  pull_request:
    types: [closed]
    branches:
      - main
permissions:
      contents: read
      packages: read
    
env:
  OCI_REGISTRY: ghcr.io
  OCI_REPOSITORY: sebascorps/helm-charts

jobs:
  deploy-helm-chart:
    environment: PRODUCTION
    runs-on: github-actions-scaleset-demo
    if: github.event.pull_request.merged == true
    steps:
        - name: checkout Repo
          uses: actions/checkout@v5
        - name: Set up Helm
          uses: azure/setup-helm@v3
          with:
            version: v3.12.0
        - name: Login to GHCR (OCI)
          run: |
            echo "${{secrets.GITHUB_TOKEN }}" | helm registry login ${{env.OCI_REGISTRY}} -u ${{ github.actor }} --password-stdin
        - name: Configure kubeconfig
          run: |
            mkdir -p $HOME/.kube
            echo "${{secrets.KUBECONFIG}}" > $HOME/.kube/config
            chmod 600 $HOME/.kube/config

        - name: Resolve latest chart version
          id: chart_version
          run: |
            TOKEN=$(curl -s -u "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}" "https://ghcr.io/token?scope=repository:${OCI_REPOSITORY}/thinknyxapp:pull&service=ghcr.io" | jq -r .token)
            LATEST_TAG=$(curl -s -H "Authorization: Bearer ${TOKEN}" "https://ghcr.io/v2/${OCI_REPOSITORY}/thinknyxapp/tags/list" | jq -r '.tags | sort | last')
            echo "version=${LATEST_TAG}" >> "$GITHUB_OUTPUT"

        - name: Deploy Helm Chart
          run: |
            helm upgrade --install thinknyxapp oci://${{env.OCI_REGISTRY}}/${{env.OCI_REPOSITORY}}/thinknyxapp --version "${{ steps.chart_version.outputs.version }}" --namespace ${{vars.NAMESPACE}} --create-namespace --wait

