name: self-hosted-runner-demo
#
on:
  push:
    branches:
      - dev   #test
jobs:
    demo-1:
      name: Demo Job 1
      runs-on: github-actions-scaleset
      steps:
        - name: Display system information
          run: |
            echo "System information:"
            echo "OS: $(uname -a)"
            echo "CPU: $(uname -m)"
            echo "Memory: $(free -h)"
            echo "Disk: $(df -h)"
            echo "Network: $(ip addr show)"
            echo "Hostname: $(hostname)"
            echo "User: $(whoami)"
            echo "Home directory: $HOME"
            echo "Current directory: $(pwd)"
            sleep 90
    demo-2:
      name: Demo Job 2
      runs-on: github-actions-scaleset
      steps:
        - name: Display system information
          run: |
            echo "System information:"
            echo "OS: $(uname -a)"
            echo "CPU: $(uname -m)"
            echo "Memory: $(free -h)"
            echo "Disk: $(df -h)"
            echo "Network: $(ip addr show)"
            echo "Hostname: $(hostname)"
            echo "User: $(whoami)"
            echo "Home directory: $HOME"
            echo "Current directory: $(pwd)"
            sleep 90